services:
  pc-humble:
    build:
      context: .
      dockerfile: Dockerfile
    image: pc_humble_image
    container_name: pc_humble
    privileged: true

    # Obrim un rang d'UDP per DDS (participant + data writers)
    ports:
      - "7400-7500:7400-7500/udp"
      - "7650-7700:7650-7700/udp"

    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=10
      - ROS_LOCALHOST_ONLY=0
      - DISPLAY=192.168.1.65:0.0   # IP del teu PC Windows amb X server
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
      - MESA_GL_VERSION_OVERRIDE=2.1
    volumes:
      - ./entrypoint.pc.sh:/entrypoint.pc.sh
    entrypoint: /entrypoint.pc.sh
    command: sleep infinity
