services:
  pc-humble:
    build:
      context: .
      dockerfile: Dockerfile
    image: pc_humble_image
    container_name: pc_humble
    privileged: true
    network_mode: host
    ipc: host
    tty: true
    stdin_open: true
    restart: unless-stopped
    # user: "${UID}:${GID}"   # opcional: exporta prèviament UID/GID

    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=10
      - ROS_LOCALHOST_ONLY=0
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
      - MESA_GL_VERSION_OVERRIDE=2.1
      # - CYCLONEDDS_URI=file:///config/cyclonedds.xml  # si el fas servir

    volumes:
      - ./entrypoint.pc.sh:/entrypoint.pc.sh:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
      # - ./config:/config:ro   # on podries tenir cyclonedds.xml
      # - ./:/work              # si vols el teu codi dins

    entrypoint: /entrypoint.pc.sh
    command: sleep infinity
